### ISSUE TITLE
Implement Local Discriminator Loss

### ISSUE THREAD

**Issue by roddtalebi** [ezCGP/ezCGP#249] opened 2022-03-01 17:44 UTC
When we are building the discriminator network, check the trainconfig dict for the flag as to whether we should also include a local discriminator loss. If so, then create another discriminator network with the genome but with smaller input size, and make sure it is incorporated into the total loss and in training.

**Comment by gabriel-q-wang** [comment] 2022-03-03 20:37
I think this might be a duplicate of #225

**Closed** 2022-03-04 16:04 UTC
